name: CI-CD Pipeline

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-project
        with:
          node-version: 22 
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [22, 24]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-project
        with:
          node-version: ${{ matrix.node-version }} 
      - run: npm test

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-project
      - run: npm audit --audit-level=high


  deploy:
    needs: [lint,test, audit]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-publish.yml
    with:
      image: ghcr.io/prashantprojectweb/ci-cd

  notify:
    needs: [lint, test, audit, deploy]
    if: always() && github.event_name =='push'
    runs-on: ubuntu-latest
    steps:
      - name: send discord message
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          RESULT: ${{ contains(needs.*.result, 'failure') && '❌ FAILED' || '✅ Success' }}
          REPO: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
          SHA: ${{ github.sha }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          MSG="$RESULT - $REPO @ ${SHA:0:7} by $ACTOR
          $RUN_URL"
          jq -n --arg content "$MSG" '{content: $content}' \
            | curl -sf -H "Content-Type: application/json" -d @- "$WEBHOOK"
          


  
  