name: CI-CD Pipeline

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-project
        with:
          node-version: 22 
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [22, 24]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-project
        with:
          node-version: ${{ matrix.node-version }} 
      - run: npm test

  deploy:
    needs: [lint,test]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-publish.yml
    with:
      image: ghcr.io/prashantprojectweb/ci-cd